### ISSUE TITLE
Refactor as PyPI package?

### ISSUE THREAD

**Issue by jharrymoore** [SMargreitter/ChemCharts#1]
Hi guys,

Really nice package, I think the plots look great.  I wondered if you'd be interested in making the repo pip installable?  Would be great to be able to easily drop this functionality into larger environments

**Comment by SMargreitter** [comment]
Hi Harry,
 
thank you for the great suggestion! I have a feature request I would like to implement first and when I am done with that I will try to make a package but that might be still a while so bear with me :)

**Comment by SMargreitter** [comment]
Hi Harry, 

ChemCharts is now available as package, thx again for the suggestion :)

Kind regards, 
Sophie
