### ISSUE TITLE
Normalization of histograms & plot colouring

### ISSUE THREAD

**Issue by MatthiasRB** [SMargreitter/ChemCharts#2]
Hi Sophie,

It would be great if there was an option to normalise the data in the plots.

E.g. In the following image, the colouring corresponds with the total number of occurrences in the chemical space visualised via umap. But if you want to compare the relative coverage of libraries of chemical space, it looks as if the smaller libraries always look much fainter due to the lower total number of occurrences. Would it be possible to have plots where plot in the histograms and colour the points via percentages of the library. So instead of 10 occurrences of a umap tile you would have perhaps 2% as a number and it corresponds to a colouring gradient?

![image](https://user-images.githubusercontent.com/59561274/152578070-b6d27db2-fa8b-42a2-930a-7d9253c29497.png)

Many thanks & best wishes,
Matthias

**Comment by SMargreitter** [comment]
Hi Matthias, 

thx for the suggestion. The current release (0.3.0) introduces the parameter "cross_object_normalize" which can be set to `false` and thereby normalizes the data per subplot (as you suggested). If the setting is `true` the hexagonal plots are normalized on all the data (which you don't want). Please let me know if that works for your data set.

Have a lovely weekend :)
Sophie

**Comment by MatthiasRB** [comment]
Hi Sophie,

Thanks so much for doing this so quickly. That works very well for our case and it makes it easier to compare the data sets.

Thanks again for your help & best wishes,
Matthias
