### ISSUE TITLE
compare UMAP space tiles between data sets

### ISSUE THREAD

**Issue by MatthiasRB** [SMargreitter/ChemCharts#3]
Hi Sophie,

WIth the new normalised data sets, it is already much easier to qualitatively / visually compare the data sets in the UMAP chemical space. Would it be possible to get a very rough quantification by counting the shared UMAP tiles between two data sets? For example data set 1 shares 85% of the tiles of data set 2. That would allow to more intuitively discussthe chemical space coverage, even if it is mathematically not completely correct due to the non-linear nature of UMAP (Christian discussed that a bit with me already). This is not urgent though. Many thanks & best wishes,
Matthias

**Comment by GuoJeff** [comment]
Hi Sophie,

Thank you for the very useful repository. I have a similar request to Matthias which I have also briefly discussed with Christian.

I am working on a project where I am interested in quantifying the hexagonal 'chemical space' overlap between adjacent epochs throughout an entire REINVENT run. For example, comparing the UMAP embedding of molecules sampled from epoch 2 with epoch 1 results in 40% overlap which would give a qualitative analysis of the sampling behaviour of successive epochs. I wanted to ask if something like this would be possible?

Thank you again for a great plotting tool!

**Comment by SMargreitter** [comment]
Hi both, 

the new release 0.5.1 will print cosine similarities between all datasets provided to the console. If you need other metrics just let me know it should be fairly easy to integrate. 

Love, 
Sophie
